app/urls.py
from . import views
from django.contrib import admin
from django.urls import path

# app_name = 'app'
urlpatterns = [
    path("index/", views.index, name='index'),
    path("house_list/", views.HouseListView.as_view(), name='house_list'),
    path('house_detail/<slug:slug>/', views.house_detail_view, name='house_detail'),
    path('house_update/<slug:slug>/', views.house_update_view, name='house_update'),
    path('house_delete/<slug:slug>/', views.house_delete, name='delete'),
    path('house_create/', views.house_create_view, name='house_create'),
]

core/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path('app/', include('app.urls')),
    path('user/', include('user.urls')),
    path('srm/', include('srm.urls')),

]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

srm/models.py
from django.db import models


class Lead(models.Model):
    full_name = models.CharField(max_length=123)
    email = models.EmailField()
    subject_line = models.CharField(blank=True, null=True, max_length=123)
    message = models.TextField()
    status = models.PositiveSmallIntegerField(
        choices=(
            (1, 'Теплый'),
            (2, 'Горячий'),
            (3, 'Мертвый'),
            (4, 'Другое')
        ),
        default=1
    )
    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.full_name

app/templates/base.html
{% load static %}


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>


    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@100;200;300;400;500;600;700;800;900&display=swap" rel="stylesheet">

    <title>Villa Agency - Real Estate HTML5 Template</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">


    <!-- Additional CSS Files -->
    <link rel="static stylesheet" href="{% static 'assets/css/fontawesome.css' %}">
    <link rel="static stylesheet" href="{% static 'assets/css/templatemo-villa-agency.css' %}">
    <link rel="static stylesheet" href="{% static 'assets/css/owl.css' %}">
    <link rel="static stylesheet" href="{% static 'assets/css/animate.css' %}">
    <link rel="static stylesheet" href="https://unpkg.com/swiper@7/swiper-bundle.min.css"/>

</head>
<body>
  <!-- ***** Preloader Start ***** -->
<!--  <div id="js-preloader" class="js-preloader">-->
<!--    <div class="preloader-inner">-->
<!--      <span class="dot"></span>-->
<!--      <div class="dots">-->
<!--        <span></span>-->
<!--        <span></span>-->
<!--        <span></span>-->
<!--      </div>-->
<!--    </div>-->
<!--  </div>-->
  <!-- ***** Preloader End ***** -->

  <div class="sub-header">
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-8">
          <ul class="info">
            <li><i class="fa fa-envelope"></i> info@company.com</li>
            <li><i class="fa fa-map"></i> Sunny Isles Beach, FL 33160</li>
          </ul>
        </div>
        <div class="col-lg-4 col-md-4">
          <ul class="social-links">
            <li><a href="#"><i class="fab fa-facebook"></i></a></li>
            <li><a href="https://x.com/minthu" target="_blank"><i class="fab fa-twitter"></i></a></li>
            <li><a href="#"><i class="fab fa-linkedin"></i></a></li>
            <li><a href="#"><i class="fab fa-instagram"></i></a></li>
          </ul>
        </div>
      </div>
    </div>
  </div>

  <!-- ***** Header Area Start ***** -->
  <header class="header-area header-sticky">
    <div class="container">
        <div class="row">
            <div class="col-12">
                <nav class="main-nav">
                    <!-- ***** Logo Start ***** -->
                    <a href="{% url 'index' %}" class="logo">
                        <h1>Villa</h1>
                    </a>
                    <!-- ***** Logo End ***** -->
                    <!-- ***** Menu Start ***** -->
                    <ul class="nav">
                      {% if request.user.status == 2 or request.user.is_admin %}
                      <li><a href="{% url 'lead_list' %}" class="active">SRM</a></li>
                      {% endif %}
                      <li><a href="{% url 'index' %}" class="active">Home</a></li>
                      <li><a href="{% url 'house_create' %}" class="active">Create record</a></li>
                      <li><a href="{% url 'house_list' %}">Properties</a></li>
                      <li><a href="{% static 'property-details.html' %}">Property Details</a></li>
                      {% if request.user.is_authenticated %}
                      <li><a href="{% url 'logout' %}">Выйти</a></li>
                      <li>
                          <a href="#"><i class="fa fa-calendar"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-person" viewBox="0 0 16 16">
                          <path d="M8 8a3 3 0 1 0 0-6 3 3 0 0 0 0 6m2-3a2 2 0 1 1-4 0 2 2 0 0 1 4 0m4 8c0 1-1 1-1 1H3s-1 0-1-1 1-4 6-4 6 3 6 4m-1-.004c-.001-.246-.154-.986-.832-1.664C11.516 10.68 10.289 10 8 10s-3.516.68-4.168 1.332c-.678.678-.83 1.418-.832 1.664z"/>
                      </svg></i>{{ request.user }}</a>
                      </li>
                      {% else %}
                      <li><a href="{% url 'register' %}">Регистрация</a></li>
                      <li><a href="{% url 'login' %}">&nbsp;&nbsp;&nbsp;&nbsp;Войти</a></li>
                      {% endif %}
                  </ul>
                    <a class='menu-trigger'>
                        <span>Menu</span>
                    </a>
                    <!-- ***** Menu End ***** -->
                </nav>
            </div>
        </div>
    </div>
  </header>
  <!-- ***** Header Area End ***** -->

{% block content %} {% endblock %}

  <footer>
    <div class="container">
      <div class="col-lg-8">
        <p>Copyright © 2048 Villa Agency Co., Ltd. All rights reserved.

        Design: <a rel="nofollow" href="https://templatemo.com" target="_blank">TemplateMo</a></p>
      </div>
    </div>
  </footer>
  <!-- Scripts -->
  <!-- Bootstrap core JavaScript -->
  <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
  <script src="{% static 'vendor/bootstrap/js/bootstrap.min.js' %}"></script>
  <script src="{% static 'assets/js/isotope.min.js' %}"></script>
  <script src="{% static 'assets/js/owl-carousel.js' %}"></script>
  <script src="{% static 'assets/js/counter.js' %}"></script>
  <script src="{% static 'assets/js/custom.js' %}"></script>
</body>
</html>